let livrosJson = [
    {id:1, name:'Uma Breve História do Tempo', img:'images/Uma Breve História do Tempo.jpeg', nota: 5, description:'Com ilustrações criativas e texto bem-humorado, Hawking desvenda desde os mistérios da física de partículas até a dinâmica das centenas de milhões de galáxias do universo. Para o iniciado, é uma bela representação de conceitos complexos; para o leigo, é um vislumbre dos segredos mais profundos da criação.', autor:'Stephen Hawking'},

    {id:2, name:'Tio Petros e a Conjectura de Goldbach', img:'images/Tio Petros.jpg', nota: 5, description:'Um jovem descobre que seu tio, um tipo estranho e visto pela família como um perdedor, fora no passado um brilhante matemático, que dedicara sua vida ao estudo de um problema insolúvel: a Conjectura de Goldbach.', autor:'Apostolos Doxiadis'},

    {id:3, name:'O Andar do Bebado', img:'images/O Andar do Bebado.jpg', nota: 5, description:'O Andar do Bêbado" é uma obra que desafia nossa compreensão do mundo, mostrando que nem tudo é determinado por uma lógica previsível. É uma leitura que nos convida a questionar nossas percepções, a abraçar a incerteza e a reconhecer a importância das probabilidades em nossas vidas.', autor:'Leonard Mlodinow'},

    {id:4, name:'O Último Desejo: A Saga do Bruxo Geralt de Rívia - Volume 1', img:'images/The Witcher 1.jpg', nota: 5, description:'Geralt de Rívia é um bruxo sagaz e habilidoso. Um assassino impiedoso e de sangue-frio treinado, desde a infância, para caçar e eliminar monstros. Seu único objetivo: destruir as criaturas do mal que assolam o mundo. Um mundo fantástico criado por Sapkowski com claras influências da mitologia eslava.', autor:'Andrzej Sapkowski'},

    {id:5, name:'A Espada do Destino: A Saga do Bruxo Geralt de Rívia - Volume 2', img:'images/The Witcher 2.jpg', nota: 5, description:'A Espada do Destino é o segundo livro da série de livros de Andrzej Sapkowski referente ao universo de The Witcher. Não faz parte da saga, é uma coletânea de contos passados antes da saga, que começa com o terceiro livro, O Sangue dos Elfos.', autor:'Andrzej Sapkowski'},

    {id:6, name:'O Sangue dos Elfos: A saga do Bruxo Geralt de Rívia - Volume 3', img:'images/The Witcher 3.jpg', nota: 5, description:'O Sangue dos Elfos é o primeiro romance da Saga Witcher escrita por Andrzej Sapkowski. É a sequência dos contos do livro O Último Desejo e A Espada do Destino, e a sua sequência é Tempo de Desprezo.', autor:'Andrzej Sapkowski'},

    {id:7, name:'Contos de Suspense e Terror', img:'images/Contos de Terror.jpg', nota: 3, description:'“Edgar Allan Poe é uma influência determinante em toda a nossa modernidade, o criador das histórias de detetive e das tramas de ficção científica, presente nas atualíssimas tendências fantásticas, góticas e underground(...)” - Eliane Fittipaldi. Esta edição possui os seguintes contos: “O coração delator”, “O gato preto”, “William Wilson”, “Metzengerstein”, “O barril de amontillado”, “A queda da casa de Usher”, “O poço e o pêndulo” e “O enterro prematuro”.', autor:'Edgar Allan Poe'},

    {id:8, name:'A Revolução dos Bichos', img:'images/A Revolução dos Bichos.jpg', nota: 4, description:'Verdadeiro clássico moderno, concebido por um dos mais influentes escritores do século XX, "A revolução dos bichos" é uma fábula sobre o poder. Narra a insurreição dos animais de uma granja contra seus donos. Progressivamente, porém, a revolução degenera numa tirania ainda mais opressiva que a dos humanos.', autor:'George Orwell'},

    {id:9, name:'Sherlock Holmes & Einstein', img:'images/Sherlock Holmes e Einstein.jpg', nota: 4, description:'Uma série de assassinatos envolvendo cientistas e o princípio do movimento perpétuo desafia a lógica e os instintos de Sherlock Holmes e Watson nesse romance policial. Enquanto ele passa por maus bocados depois de ter ingerido uma beberagem muito suspeita, Sherlock Holmes é sequestrado por um grupo de bolcheviques exilados, perseguido por uma sufragista socialista e acaba se ligando a um desconhecido chamado Albert Einstein.', autor:'Alexis Lecaye'},

    {id:10, name:'Subliminar', img:'images/Subliminar.jpg', nota: 3, description:'Você acha que sabe como e por que faz suas escolhas? Suas preferências políticas, a gorjeta que dá ao garçom, aquele colega de trabalho com uma cara tão amigável de quem você desconfia e até a pessoa com quem você se casa não são opções tão objetivas assim. Leonard Mlodinow investiga, de forma divertida e brilhante, como o inconsciente modela nosso comportamento e determina nossas decisões e juízos sobre o mundo, as pessoas, as coisas. Um livro que vai mudar a sua vida.', autor:'Leonard Mlodinow'},

    {id:11, name:'Morte no Nilo', img:'images/Morte no Nilo.jpg', nota: 5, description:'A tranquilidade de um cruzeiro de luxo pelo Nilo chega ao fim quando o corpo de Linnet Doyle, uma bela e jovem milionária, é descoberto em sua cabine. Porém, para azar do autor do crime, o brilhante detetive Hercule Poirot está a bordo. Ele logo descobre que cada passageiro é suspeito, pois todos tinham motivos para tirar a vida de Linnet. Em um rio de mentiras, Poirot precisa descobrir a verdade sobre esse estranho assassinato.', autor:'Agatha Christie'},

    {id:12, name:'O Cão dos Baskervilles', img:'images/O Cão dos Baskervilles.jpg', nota: 5, description:'Sherlock Holmes, ao lado do Dr. Watson, investiga a misteriosa morte de Sir Charles Baskerville. No centro do caso, um suposto cão assassino e sobrenatural, que assombra a família Baskerville, cujo último herdeiro teme pela vida, depois de receber um enigmático bilhete. Com muitas pistas desencontradas e uma aterradora mansão com mais de 500 anos, Holmes precisa se valer de toda a sua argúcia para identificar os verdadeiros culpados.', autor:'Arthur Conan Doyle '},

    {id:13, name:'Biblioteca H.P. Lovecraft', img:'images/Lovecraft.jpg ', nota: 5, description:'Primeiro volume da coleção que publicará as histórias completas de Lovecraft, o escritor que revolucionou a literatura de horror. Neste primeiro volume da série “Biblioteca Lovecraft”  encontramos textos clássicos como “O chamado de Cthulhu” e “A sombra de Innsmouth”, e também textos menos conhecidos como “Dagon” (espécie de breve preâmbulo aos mitos de Cthulhu).', autor:'H. P. Lovecraft '},

    {id:14, name:'Arsène Lupin, o ladrão de casaca', img:'images/Arsene lupin.jpg ', nota: 5, description:'Este livro reúne as nove histórias A prisão de Arsène Lupin, Arsène Lupin na prisão, A fuga de Arsène Lupin, O viajante misterioso, O colar da rainha, O sete de copas, O cofre de Madame Imbert, A pérola negra e outros. ', autor:'Maurice Leblanc'},

];   